<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-4" name="com.focus.testcases.SalesOrderVoucherTest" tests="18" failures="2" timestamp="23 Jul 2021 15:20:09 GMT" time="753.591" errors="0">
  <testcase name="checkSavingSalesOrderVoucher2WithStockItem" time="18.062" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkVerifingDetailsOfSavedSalesOrderVoucherInHomepage" time="9.634" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkSavingSalesOrderVoucherWithBinItem" time="72.646" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkSavingSalesOrderVoucher5WithRmaItem" time="27.461" classname="com.focus.testcases.SalesOrderVoucherTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.SalesOrderVoucherTest.checkSavingSalesOrderVoucher5WithRmaItem(SalesOrderVoucherTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingSalesOrderVoucher5WithRmaItem -->
  <testcase name="checkSavingSalesOrderVoucher2WithBatchItem" time="76.672" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkEditingSalesOrderVoucher3AndAdding2ndRow" time="77.313" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkSavingSalesOrderVoucher3WithStockItem" time="17.656" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkEditingSalesOrderVoucher4AndAdding2ndRow" time="36.574" classname="com.focus.testcases.SalesOrderVoucherTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.SalesOrderVoucherTest.checkEditingSalesOrderVoucher4AndAdding2ndRow(SalesOrderVoucherTest.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditingSalesOrderVoucher4AndAdding2ndRow -->
  <testcase name="checkSavingSalesOrderVoucher4WithBinItem" time="76.733" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkSavingSalesOrderVoucher1WithBatchItem" time="79.778" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkSavingSalesOrderVoucherWithRmaItem" time="36.242" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkVerifyingSalesOrderVoucher5AndDeleting" time="12.428" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkEditingSalesOrderVoucher1AndAdding2ndRow" time="74.307" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkSalesOrderVoucherCustomization" time="101.704" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkVerifyingSalesOrderVoucher4AndDeleting" time="10.274" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkVerifyingSalesOrderVoucher3AndDeleting" time="3.086" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkVerifyingSalesOrderVoucher2AndDeleting" time="3.142" classname="com.focus.testcases.SalesOrderVoucherTest"/>
  <testcase name="checkEditingSalesOrderVoucher2AndAdding2ndRow" time="19.879" classname="com.focus.testcases.SalesOrderVoucherTest"/>
</testsuite> <!-- com.focus.testcases.SalesOrderVoucherTest -->
